eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1001/eureka/
server:
    port: 7002
spring:
    application:
        name: config-client
    cloud:
        config:
            discovery:
                enabled: true
                serviceId: config-server
            profile: dev
