eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1001/eureka/
server:
    port: 9002
spring:
    application:
        name: swagger-service-b

swagger:
    base-package: com.example.swaggerserviceb
